2025-06-13 14:06:20,446 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 14:06:20,768 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 15:43:27,741 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 15:43:27,922 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 16:29:36,811 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:29:36,970 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:29:40,597 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:29:40,648 - document_validation - INFO - [elasticsearch_utils.py:73] - Retrieved 1 rules for service ID: 1
2025-06-13 16:29:52,693 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:29:52,842 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:38:04,541 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:38:16,370 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:38:47,497 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:39:01,409 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:39:20,391 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:39:48,663 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:40:02,665 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:40:06,037 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:40:23,320 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:40:33,352 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:41:01,891 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:41:15,335 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:41:21,878 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:41:34,618 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:41:50,337 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:41:57,061 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:42:01,957 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:42:13,990 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:42:23,731 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:42:28,113 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:42:32,756 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:42:36,593 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:42:38,442 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:42:40,223 - document_validation - INFO - [elasticsearch_utils.py:73] - Retrieved 1 rules for service ID: 1
2025-06-13 16:44:30,610 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:44:30,756 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:44:39,424 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:44:48,992 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:44:49,642 - document_validation - INFO - [elasticsearch_utils.py:73] - Retrieved 1 rules for service ID: 1
2025-06-13 16:46:14,559 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:46:14,718 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:46:18,478 - document_validation - INFO - [elasticsearch_utils.py:35] - Elasticsearch connection established successfully
2025-06-13 16:46:19,094 - document_validation - INFO - [elasticsearch_utils.py:73] - Retrieved 1 rules for service ID: 1
2025-06-13 17:26:27,311 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:26:27,491 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:26:30,331 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:26:30,346 - document_validation - ERROR - [elasticsearch_utils.py:78] - Error retrieving compliance rules: 'NoneType' object has no attribute 'search'
2025-06-13 17:26:48,562 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:26:49,766 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:26:49,788 - document_validation - ERROR - [elasticsearch_utils.py:78] - Error retrieving compliance rules: 'NoneType' object has no attribute 'search'
2025-06-13 17:27:10,998 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:27:12,584 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:27:12,928 - document_validation - ERROR - [elasticsearch_utils.py:78] - Error retrieving compliance rules: 'NoneType' object has no attribute 'search'
2025-06-13 17:27:33,842 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:27:39,084 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:27:44,655 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:27:50,425 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:27:57,011 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:27:58,604 - document_validation - ERROR - [elasticsearch_utils.py:32] - Elasticsearch connection failed
2025-06-13 17:27:59,037 - document_validation - ERROR - [elasticsearch_utils.py:78] - Error retrieving compliance rules: 'NoneType' object has no attribute 'search'
